### ISSUE TITLE
Feedback: relocating 'How to write a Smart-Contract' section? 

### ISSUE THREAD

**Issue by taomo-eo** [abalu/NeoSmartAddress#1]
[How to Write a Smart-Contract](https://github.com/abalu/NeoSmartAddress/wiki#how-to-write-a-smart-contract)

The section explores very helpful questions to why someone would want to write smart contracts, or why smart contracts are valuable. 
However, it reads somewhat jarring in its current position, after the reader is already knee deep into setting up SC environments and deploying SCs. Would it be more fitting to put this section before '[Developing Stages](https://github.com/abalu/NeoSmartAddress/wiki#developing-stages-local-neo-privatenet-neo-testnet-neo-mainnet)'? 

Just a thought. Otherwise, I've found this tutorial to be clear, thorough and very helpful. Well done!

**Comment by abalu** [comment]
You are totally right!
MY bad.
Good advice - I just adopted it.
